#          Copyright Dominic (DNKpp) Koepke 2024 - 2025.
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          https://www.boost.org/LICENSE_1_0.txt)

name: "Release adapter headers"

on:
  release:
    types: [ released ]

jobs:
  release-headers:
    runs-on: ubuntu-latest

    # this is required for the asset attachment
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Attach adapter headers as release asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: "include/mimic++_ext/adapters/*.hpp"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          omitBody: true
          omitName: true
